apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-basic
  namespace: argocd
spec:
  destination:
    namespace: project-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx-basic
    repoURL: https://github.com/yogeek/argocd-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        webhooks.kyverno.io/exclude: "true"
        owner: gtp
      annotations:
        test: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
